import { 
  MenuItem, 
  Table, 
  PaymentMethod, 
  Discount, 
  User, 
  MenuCategory,
  ModifierGroup,
  Modifier,
  BusinessPartner,
  Shift,
  PosTerminal,
  BusinessUnit,
  KitchenDisplayItem,
  InventoryAlert,
  SalesMetrics
} from '@/types/pos-types';

export const mockBusinessUnit: BusinessUnit = {
  id: '1',
  name: 'Downtown Restaurant',
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockUsers: User[] = [
  { id: '1', name: 'John Smith', username: 'jsmith', isActive: true, role: 'Server' },
  { id: '2', name: 'Sarah Johnson', username: 'sjohnson', isActive: true, role: 'Server' },
  { id: '3', name: 'Mike Wilson', username: 'mwilson', isActive: true, role: 'Manager' },
  { id: '4', name: 'Emma Davis', username: 'edavis', isActive: true, role: 'Server' },
  { id: '5', name: 'Alex Chen', username: 'achen', isActive: true, role: 'Bartender' },
];

export const mockTerminal: PosTerminal = {
  id: '1',
  name: 'Main Terminal',
  description: 'Primary POS Terminal',
  isActive: true,
  businessUnitId: '1',
};

export const mockShift: Shift = {
  id: '1',
  businessUnitId: '1',
  userId: '1',
  user: mockUsers[0],
  terminalId: '1',
  startedAt: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
  startingCash: 200.00,
  totalSales: 1250.75,
  totalOrders: 23,
};

export const mockModifiers: Modifier[] = [
  { id: '1', name: 'Extra Cheese', priceChange: 2.50, modifierGroupId: '1' },
  { id: '2', name: 'No Onions', priceChange: 0, modifierGroupId: '1' },
  { id: '3', name: 'Extra Bacon', priceChange: 3.00, modifierGroupId: '1' },
  { id: '4', name: 'Gluten Free Bun', priceChange: 1.50, modifierGroupId: '1' },
  { id: '5', name: 'Medium Rare', priceChange: 0, modifierGroupId: '2' },
  { id: '6', name: 'Well Done', priceChange: 0, modifierGroupId: '2' },
  { id: '7', name: 'Caesar Dressing', priceChange: 0, modifierGroupId: '3' },
  { id: '8', name: 'Ranch Dressing', priceChange: 0, modifierGroupId: '3' },
];

export const mockModifierGroups: ModifierGroup[] = [
  {
    id: '1',
    name: 'Burger Add-ons',
    businessUnitId: '1',
    required: false,
    maxSelections: 5,
    modifiers: mockModifiers.slice(0, 4),
  },
  {
    id: '2',
    name: 'Meat Temperature',
    businessUnitId: '1',
    required: true,
    maxSelections: 1,
    modifiers: mockModifiers.slice(4, 6),
  },
  {
    id: '3',
    name: 'Dressing Choice',
    businessUnitId: '1',
    required: true,
    maxSelections: 1,
    modifiers: mockModifiers.slice(6, 8),
  },
];

export const mockMenuCategories: MenuCategory[] = [
  {
    id: '1',
    name: 'Appetizers',
    description: 'Start your meal right',
    isActive: true,
    businessUnitId: '1',
    prepStation: 'Cold Kitchen',
    imageUrl: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    sortOrder: 1,
  },
  {
    id: '2',
    name: 'Burgers',
    description: 'Gourmet burgers made fresh',
    isActive: true,
    businessUnitId: '1',
    prepStation: 'Hot Kitchen',
    imageUrl: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    sortOrder: 2,
  },
  {
    id: '3',
    name: 'Salads',
    description: 'Fresh and healthy options',
    isActive: true,
    businessUnitId: '1',
    prepStation: 'Cold Kitchen',
    imageUrl: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg',
    sortOrder: 3,
  },
  {
    id: '4',
    name: 'Main Course',
    description: 'Hearty main dishes',
    isActive: true,
    businessUnitId: '1',
    prepStation: 'Hot Kitchen',
    imageUrl: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
    sortOrder: 4,
  },
  {
    id: '5',
    name: 'Desserts',
    description: 'Sweet endings',
    isActive: true,
    businessUnitId: '1',
    prepStation: 'Pastry Station',
    imageUrl: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    sortOrder: 5,
  },
  {
    id: '6',
    name: 'Beverages',
    description: 'Refreshing drinks',
    isActive: true,
    businessUnitId: '1',
    prepStation: 'Bar',
    imageUrl: 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg',
    sortOrder: 6,
  },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Truffle Arancini',
    description: 'Crispy risotto balls with truffle oil and parmesan',
    price: 14.99,
    imageUrl: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    isActive: true,
    categoryId: '1',
    category: mockMenuCategories[0],
    businessUnitId: '1',
    preparationTime: 12,
    allergens: ['dairy', 'gluten'],
    nutritionalInfo: { calories: 320, protein: 12, carbs: 28, fat: 18 },
  },
  {
    id: '2',
    name: 'Classic Cheeseburger',
    description: 'Angus beef patty with aged cheddar, lettuce, tomato, onion',
    price: 18.99,
    imageUrl: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    isActive: true,
    categoryId: '2',
    category: mockMenuCategories[1],
    businessUnitId: '1',
    preparationTime: 15,
    allergens: ['dairy', 'gluten'],
    nutritionalInfo: { calories: 650, protein: 35, carbs: 45, fat: 38 },
    modifierGroups: [mockModifierGroups[0], mockModifierGroups[1]],
  },
  {
    id: '3',
    name: 'Mediterranean Quinoa Bowl',
    description: 'Quinoa, roasted vegetables, feta, olives, tahini dressing',
    price: 16.99,
    imageUrl: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg',
    isActive: true,
    categoryId: '3',
    category: mockMenuCategories[2],
    businessUnitId: '1',
    preparationTime: 10,
    allergens: ['dairy'],
    nutritionalInfo: { calories: 420, protein: 18, carbs: 52, fat: 16 },
    modifierGroups: [mockModifierGroups[2]],
  },
  {
    id: '4',
    name: 'Grilled Atlantic Salmon',
    description: 'Fresh salmon with lemon herb butter, seasonal vegetables',
    price: 28.99,
    imageUrl: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
    isActive: true,
    categoryId: '4',
    category: mockMenuCategories[3],
    businessUnitId: '1',
    preparationTime: 18,
    allergens: ['fish'],
    nutritionalInfo: { calories: 480, protein: 42, carbs: 12, fat: 28 },
  },
  {
    id: '5',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, vanilla ice cream',
    price: 9.99,
    imageUrl: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    isActive: true,
    categoryId: '5',
    category: mockMenuCategories[4],
    businessUnitId: '1',
    preparationTime: 8,
    allergens: ['dairy', 'eggs', 'gluten'],
    nutritionalInfo: { calories: 520, protein: 8, carbs: 65, fat: 24 },
  },
  {
    id: '6',
    name: 'Craft Beer Selection',
    description: 'Local IPA, Wheat Beer, or Stout',
    price: 6.99,
    imageUrl: 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg',
    isActive: true,
    categoryId: '6',
    category: mockMenuCategories[5],
    businessUnitId: '1',
    preparationTime: 2,
    allergens: ['gluten'],
  },
  {
    id: '7',
    name: 'Wagyu Beef Sliders',
    description: 'Three mini wagyu sliders with caramelized onions',
    price: 24.99,
    imageUrl: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    isActive: true,
    categoryId: '1',
    category: mockMenuCategories[0],
    businessUnitId: '1',
    preparationTime: 14,
    allergens: ['dairy', 'gluten'],
    nutritionalInfo: { calories: 580, protein: 32, carbs: 36, fat: 34 },
  },
  {
    id: '8',
    name: 'Lobster Mac & Cheese',
    description: 'Fresh lobster with truffle mac and cheese',
    price: 32.99,
    imageUrl: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
    isActive: true,
    categoryId: '4',
    category: mockMenuCategories[3],
    businessUnitId: '1',
    preparationTime: 16,
    allergens: ['dairy', 'gluten', 'shellfish'],
    nutritionalInfo: { calories: 720, protein: 38, carbs: 48, fat: 42 },
  },
];

export const mockTables: Table[] = [
  { id: '1', name: 'Table 1', businessUnitId: '1', status: 'AVAILABLE', capacity: 2, section: 'Main Dining' },
  { id: '2', name: 'Table 2', businessUnitId: '1', status: 'OCCUPIED', capacity: 4, waiter: mockUsers[0], section: 'Main Dining' },
  { id: '3', name: 'Table 3', businessUnitId: '1', status: 'AVAILABLE', capacity: 6, section: 'Main Dining' },
  { id: '4', name: 'Table 4', businessUnitId: '1', status: 'RESERVED', capacity: 2, section: 'Main Dining' },
  { id: '5', name: 'Table 5', businessUnitId: '1', status: 'AVAILABLE', capacity: 4, section: 'Main Dining' },
  { id: '7', name: 'Table 6', businessUnitId: '1', status: 'OCCUPIED', capacity: 2, waiter: mockUsers[1], section: 'Main Dining' },
  { id: '8', name: 'Table 7', businessUnitId: '1', status: 'AVAILABLE', capacity: 4, section: 'Main Dining' },
  { id: '13', name: 'Table 8', businessUnitId: '1', status: 'AVAILABLE', capacity: 1, section: 'Main Dining' },
  { id: '14', name: 'Table 9', businessUnitId: '1', status: 'OCCUPIED', capacity: 1, waiter: mockUsers[4], section: 'Main Dining' },
  { id: '15', name: 'Table 10', businessUnitId: '1', status: 'AVAILABLE', capacity: 1, section: 'Main Dining' },
    { id: '16', name: 'Table 11', businessUnitId: '1', status: 'AVAILABLE', capacity: 1, section: 'Main Dining' },
      { id: '17', name: 'Table 12', businessUnitId: '1', status: 'AVAILABLE', capacity: 1, section: 'Main Dining' },
];

export const paymentMethods: PaymentMethod[] = [
  { id: '1', name: 'Cash', type: 'cash', icon: 'Banknote', isActive: true },
  { id: '2', name: 'Credit Card', type: 'card', icon: 'CreditCard', isActive: true, processingFee: 2.9 },
  { id: '3', name: 'Debit Card', type: 'card', icon: 'CreditCard', isActive: true, processingFee: 1.5 },
  { id: '4', name: 'GCash', type: 'ewallet', icon: 'Smartphone', isActive: true, processingFee: 1.0 },
  { id: '5', name: 'PayMaya', type: 'ewallet', icon: 'Smartphone', isActive: true, processingFee: 1.0 },
  { id: '6', name: 'Bank Transfer', type: 'bank_transfer', icon: 'Building2', isActive: true },
];

export const discounts: Discount[] = [
  { 
    id: '1', 
    name: 'Senior Citizen', 
    type: 'PERCENTAGE', 
    value: 20, 
    businessUnitId: '1', 
    isActive: true,
    description: '20% discount for senior citizens'
  },
  { 
    id: '2', 
    name: 'Student Discount', 
    type: 'PERCENTAGE', 
    value: 15, 
    businessUnitId: '1', 
    isActive: true,
    description: '15% discount for students with valid ID'
  },
  { 
    id: '3', 
    name: 'Happy Hour', 
    type: 'PERCENTAGE', 
    value: 25, 
    businessUnitId: '1', 
    isActive: true,
    description: '25% off beverages 3-6 PM'
  },
  { 
    id: '4', 
    name: 'First Time Customer', 
    type: 'FIXED_AMOUNT', 
    value: 10, 
    businessUnitId: '1', 
    isActive: true,
    description: '$10 off first order'
  },
  { 
    id: '5', 
    name: 'Staff Meal', 
    type: 'PERCENTAGE', 
    value: 50, 
    businessUnitId: '1', 
    isActive: true,
    description: '50% staff discount'
  },
];

export const mockBusinessPartners: BusinessPartner[] = [
  {
    id: '1',
    name: 'John Doe',
    phone: '+1234567890',
    email: 'john.doe@email.com',
    loyaltyPoints: 1250,
    membershipTier: 'GOLD',
    totalSpent: 2500.00,
    lastVisit: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: '2',
    name: 'Jane Smith',
    phone: '+1234567891',
    email: 'jane.smith@email.com',
    loyaltyPoints: 750,
    membershipTier: 'SILVER',
    totalSpent: 1500.00,
    lastVisit: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
];

export const mockKitchenItems: KitchenDisplayItem[] = [
  {
    id: '1',
    orderItem: {
      id: '1',
      orderId: '1',
      menuItemId: '2',
      menuItem: mockMenuItems[1],
      quantity: 2,
      priceAtSale: 18.99,
      kdsStatus: 'PREPARING',
      isVoided: false,
      modifiers: [mockModifiers[0], mockModifiers[4]],
      addedAt: new Date(Date.now() - 10 * 60 * 1000),
    },
    order: {
      id: '1',
      businessUnitId: '1',
      tableId: '2',
      userId: '1',
      user: mockUsers[0],
      terminalId: '1',
      status: 'PREPARING',
      orderType: 'Dine-In',
      items: [],
      subTotal: 37.98,
      discountValue: 0,
      tax: 3.80,
      totalAmount: 41.78,
      amountPaid: 0,
      isPaid: false,
      createdAt: new Date(Date.now() - 10 * 60 * 1000),
      updatedAt: new Date(),
    },
    prepStation: 'Hot Kitchen',
    estimatedTime: 15,
    startedAt: new Date(Date.now() - 5 * 60 * 1000),
    priority: 'NORMAL',
  },
];

export const mockInventoryAlerts: InventoryAlert[] = [
  {
    id: '1',
    itemName: 'Angus Beef Patties',
    currentStock: 5,
    reorderPoint: 20,
    severity: 'CRITICAL',
  },
  {
    id: '2',
    itemName: 'Fresh Salmon',
    currentStock: 8,
    reorderPoint: 15,
    severity: 'LOW',
  },
];

export const mockSalesMetrics: SalesMetrics = {
  totalSales: 3250.75,
  totalOrders: 45,
  averageOrderValue: 72.24,
  topSellingItems: [
    { item: mockMenuItems[1], quantity: 12, revenue: 227.88 },
    { item: mockMenuItems[3], quantity: 8, revenue: 231.92 },
    { item: mockMenuItems[2], quantity: 10, revenue: 169.90 },
  ],
  hourlyBreakdown: [
    { hour: 11, sales: 245.50, orders: 4 },
    { hour: 12, sales: 567.25, orders: 8 },
    { hour: 13, sales: 892.75, orders: 12 },
    { hour: 14, sales: 445.25, orders: 6 },
    { hour: 15, sales: 325.00, orders: 5 },
    { hour: 16, sales: 775.00, orders: 10 },
  ],
};